### ISSUE TITLE
Reorganize Hack Night schedule for more hacking?

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/hack-night-planning#66]
### High-level goals

- Introduce basic info about CfM and HN's
- Provide 20-30 minutes for a speaker
- Have lots of time for open hacking
- things to avoid:
   - rushing the speaker to finish too quickly
   - scheduling the speaker too close to 6pm so stragglers miss it
   - getting to hacking too late

### Suggestions:

1. Let’s move the new member orientation until after the introduction of breakout groups. What’s the advantages and disadvantages?
2. Perhaps shorten the presentation to 20 minutes and communicate that the presenter will have a “breakout group”?

**Comment by Aycrazy** [comment]
mitchellhenke 8:44 AM
I think future hack nights should make more time for open time for hacking. Had a couple people mention it to me and I agree. One had to leave by 8 and was disappointed they didn’t get much time to work on stuff with everything else beforehand

**Comment by anthonyjesmok** [comment]
Draft Schedule, please let me know your thoughts.

6:00 to 6:15 - Arrival, Registration, Food Service
6:15 to 6:25 - Welcome from Code for Milwaukee
6:25 to 6:45 - Presentation (Save Questions for Q&A)
6:45 to 6:50 - Presentation Q&A
6:50 to 7:00 - Breakout Group Introductions
- Speaker will have a breakout group for discussing their presentation, ideas, detailed questions, etc.
- New breakout groups MUST be registered at https://forms.gle/6ZKzKj2HKG5bMq8j6 in order to receive introductory time.
7:00 to 9:00 - Open Collaboration and Hacking
9:00 to 9:10 - Updates from the Groups, Next Steps Discussion, Announcements
9:30 - Hard Stop, Doors Closed and Locked

**Comment by mitchellhenke** [comment]
I think we should be more aggressive and aim to start hacking by ~6:30-6:40

Is it possible to have doors open at 5:45, shorten welcome, and perhaps introduce existing working groups on a presentation slide? The person leading the group can wave so anyone interested can find them to discuss further. Any new working groups would still verbally introduce themselves.

**Comment by anthonyjesmok** [comment]
My thoughts on starting before 6 would involve people who are further out
(like Kohl's and NM in Franklin) and need to get through rush hour traffic
to make it over to the event.

**Comment by Aycrazy** [comment]
To @mitchellhenke's suggestion about existing groups. I think that can work alright, if we can get ppl to view videos and the github issues page for a project independently. --> Please help to think about how we can make that something people do (this is hard)

I also mentioned having **orientation recorded**, this will free up time for ppl to network at the beginning if they already watched a recording (before coming to their first hack night), free up most of the time of whichever core team member (Erin or Brian) would do the orientation, and give ppl the ability to review anything they found confusing (then they could also independently ask questions). This requires us to think about if orientation is well-developed enough for this, or if there is anything that ppl think needs to be added, changed or experimented with about it.

**Comment by anthonyjesmok** [comment]
> To @mitchellhenke's suggestion about existing groups. I think that can work alright, if we can get ppl to view videos and the github issues page for a project independently. --> Please help to think about how we can make that something people do (this is hard)
> 
> I also mentioned having **orientation recorded**, this will free up time for ppl to network at the beginning if they already watched a recording (before coming to their first hack night), free up most of the time of whichever core team member (Erin or Brian) would do the orientation, and give ppl the ability to review anything they found confusing (then they could also independently ask questions). This requires us to think about if orientation is well-developed enough for this, or if there is anything that ppl think needs to be added, changed or experimented with about it.

Having the orientation recorded would be a great idea. It would mean we would only have to reserve one room and can have all core team members focused at the same time. People can also complete a quiz on orientation when they are done and formally register to be a CfM member.

**Comment by BarkleyBG** [comment]
I'm not sure if I've thought about a videotaped orientation. I would certainly like some help in plotting out a short script for that if we go in that direction

**Comment by anthonyjesmok** [comment]
@BarkleyBG @Aycrazy @mitchellhenke @romkedehaan @Dannycap @erinmagennis 

I feel we need to call this to a vote. Please react with a thumbs-up or thumbs-down emoji (using the +:) button above).

I move that we should:
1. Move orientation to a pre-recorded format that can be accessed via YouTube or another video platform.
2. Implement #67 for October hack night as a consolidated way to share venue information, schedule, etc.

**Comment by BarkleyBG** [comment]
I think we should plan out what this new precanned orientation would look like, and then cote if we want to go with the new precanned version

**Comment by romkedehaan** [comment]
Can we do have a working group around it?

**Comment by BarkleyBG** [comment]
Let's start to compile our thoughts in this document. We should consider what we want in these two items, and how we can do them. 
https://docs.google.com/document/d/157EWI1xyPzwiNwpnuXeBCx3dzknp13Uwvh9--2JTZoo/edit#heading=h.8evjuh8ec5yx

**Comment by BarkleyBG** [comment]
We will plan to discuss this in Wednesday’s phone call.

**Comment by Aycrazy** [comment]
How to earn your membership badge --> whatever physical form it takes
- At least showing that you completed the interactive portion of the orientation

**Comment by Aycrazy** [comment]
Draft to be posted for Meetup until we finalize:

6:00 to 6:15 - Arrival, Registration, Food Service
6:15 to 6:20 - Welcome from Code for Milwaukee
6:20 to 6:40 - Presentation (Save Questions for Q&A)
6:40 to 6:45 - Presentation Q&A
6:47 to 6:57 - Breakout Group Introductions
New members need to attend Orientation in a separate space before starting to contribute to CfM.
Speaker will have a breakout group for discussing their presentation, ideas, detailed questions, etc.
New breakout groups MUST be registered at https://forms.gle/6ZKzKj2HKG5bMq8j6 in order to receive introductory time.
7:00 to 9:00 - Open Collaboration and Hacking
9:00 to 9:10 - Updates from the Groups, Next Steps Discussion, Announcements
9:30 - Hard Stop, Doors Closed and Locked

**Comment by anthonyjesmok** [comment]
Updating:

6:00 to 6:15 - Arrival, Registration, Food Service
6:15 to 6:20 - Welcome from Code for Milwaukee
6:20 to 6:40 - Presentation (Save Questions for Q&A)
6:40 to 6:45 - Presentation Q&A
6:45 to 7:00 - Breakout Group Introductions
New members need to attend Orientation in a separate space before starting to contribute to CfM.
Speaker will have a breakout group for discussing their presentation, ideas, detailed questions, etc.
New breakout groups MUST be registered at https://forms.gle/6ZKzKj2HKG5bMq8j6 in order to receive introductory time.
7:00 to 9:00 - Open Collaboration and Hacking
9:00 to 9:10 - Updates from the Groups, Next Steps Discussion, Announcements
9:30 - Hard Stop, Doors Closed and Locked

**Comment by Aycrazy** [comment]
I think we've nailed this

**Comment by BarkleyBG** [comment]
Let's be sure to invite the host/sponsor to give a 5 min talk
