### ISSUE TITLE
Write thank you template for event speakers

### ISSUE THREAD

**Issue by Aycrazy** [codeformilwaukee/hack-night-planning#70]
We can make an adaptable thank you email template. We need to thank speakers from the last (2?) Hack nights and NDCOH. I will post a doc with some of my past thank yous here later. That said, if anyone wanted to get started, don't let the doc link posting delay you.

**Comment by BarkleyBG** [comment]
Beyond just a “thank you”, what else should we communicate in this letter? Should we attempt to tie their actions to our mission statement? 


For example, “thank you for speaking at our event; it’s important because people now are even more excited and motivated to help improve Milwaukee through civic tech and (your initiative)”

**Comment by Aycrazy** [comment]
That sounds great!! And something about how we want to continue the collaboration or partnership in some relevant and specific way

**Comment by Aycrazy** [comment]
React Traning info: Code for Milwaukee members can use CodeForMKE for a free ticket:
https://www.eventbrite.com/e/building-your-first-react-app-tickets-73364488159

**Comment by anthonyjesmok** [comment]
It looks like this was taken care of? How can I help further?

**Comment by Aycrazy** [comment]
Think we're good!
